### ISSUE TITLE
Implement SSL/wss across all clients

### ISSUE THREAD

**Issue by black-sliver** [ArchipelagoMW/Archipelago#1647]
### What task needs to be completed?

The server can currently run either in SSL (wss) or plain (ws) mode. Clients will most likely have to support both for cases where a locally-hosted MultiServer can't have a valid certificate but archipelago.gg requires SSL.

## Implementation

The client/client libs should try both SSL (wss://...) and plain (ws://...) when being supplied just `server:port`.

In addition to that, where possible, it would be good to allow the user to explicitly select ws or wss by having them enter a full URL (i.e. `/connect ws://...` vs. `/connect wss://...`).

## Testing

While there is no RC/beta active, http://archipelago:gg:24242 will spin up games in SSL-enabled mode.

There is also an SSL-enabled test room hosted on wss://archipelago.gg:12121

## Progress of client libs
*If you know if a lib already works mark as done or leave a comment.*

- [x] [apclientpp](https://github.com/black-sliver/apclientpp): https://github.com/black-sliver/apclientpp/commit/034589499fcac743eb9af7bb2fc5d3d879321153 - requires update wswrap on Desktop
- [x] [APCpp](https://github.com/N00byKing/APCpp)
- [x] [archipelago.js](https://www.npmjs.com/package/archipelago.js)
- [x] [Archipelago.MultiClient.Java](https://github.com/ArchipelagoMW/Archipelago.MultiClient.Java)
- [x] [Archipelago.MultiClient.Net](https://www.nuget.org/packages/Archipelago.MultiClient.Net) - auto-select since v5.0.0
- [x] [ArchipelagoRS](https://github.com/ryanisaacg/archipelago_rs) - implemented in https://github.com/ryanisaacg/archipelago_rs/commit/da97d068c289d5aec898d61abad05d7c361632f1
- [x] [hxArchipelago](https://lib.haxe.org/p/hxArchipelago)
- [x] [lua-apclientpp](https://github.com/black-sliver/lua-apclientpp/)
- [x] [py](https://github.com/ArchipelagoMW/Archipelago/blob/main/CommonClient.py): #1341
- [x] various lua libs? People that were asked said theirs work.

### WSS proxies
* [Phar's archipelago_wss_proxy](https://github.com/ThePhar/archipelago_wss_proxy)

### Helper libs
* [c-wspp-websocket-sharp](https://github.com/black-sliver/c-wspp-websocket-sharp) - fake websocket-sharp.dll for Archipelago.MultiClient.Net that uses a native WebSocket with OpenSSL support under the hood. ~~Test build [in Discord](https://discord.com/channels/731205301247803413/1043855558303821844/1153488980826914868).~~ Now with [Automated Builds](https://github.com/black-sliver/c-wspp-websocket-sharp/releases/).

## Progress of game clients
*Insert games here that are known to not work or need to update the client lib to work. If you know one works already, mark as done or leave a comment.*

- [x] Meritous
- [x] DS3
- [x] Witness
- [x] HK
- [x] Subnautica: does ws:// <-> wss:// in the mod
- [x] SA2B
- [x] SM64ex
- [x] Rogue Legacy (needs [Pre-release 1.0.0 Alpha 4 or newer](https://github.com/ThePhar/RogueLegacyRandomizer/releases))
- [x] VVVVVV
- [x] Minecraft
- [x] DLC Quest
- [x] Stardew Valley
- [x] StS
- [x] Overcooked 2
- [x] Messenger
- [x] Hylics 2
- [x] Blasphemous
- [x] Bumper Stickers
- [x] DOOM 1993
- [x] Muse Dash
- [x] Noita
- [x] Terraria

### Unsupported clients
- [x] AHiT uses [phar's proxy](https://github.com/ThePhar/archipelago_wss_proxy)

**Comment by Berserker66** [comment]
Subnautica works with recent versions if the user submits the full wss url. No automatic detection, hoping that will happen on the library layer.

**Comment by Jarno458** [comment]
its on my TODO list to add automatic wss if the user does not supply a protocol

**Comment by ThePhar** [comment]
archipelago.js has been updated to support wss://

![image](https://user-images.githubusercontent.com/11338376/230960848-e1e71c9e-4ead-481f-af79-edc8b50f62f1.png)
![image](https://user-images.githubusercontent.com/11338376/230960854-c28fda6e-ce5c-4ae9-b4f0-f788582743ce.png)

**Comment by N00byKing** [comment]
APCpp now supports automatic SSL. I haven't updated the games yet, currently not home.

**Comment by ThePhar** [comment]
archipelago.js 0.6.0 will support automatic SSL. Clique has been updated to use it. Will be pushing it to npm later this weekend.

**Comment by heinermann** [comment]
Timespinner also only works if you enter `wss://` yourself in the server field.

**Comment by agilbert1412** [comment]
Stardew Valley: Seems to work only if the user inputs wss:// manually. Not ideal, but usable
DLCQuest: Does not work at all, regardless of how the user tries it. Will need to touch base with Jarno on Multiclient.Net

**Comment by KonoTyran** [comment]
Archipelago.multiclient.java does support wss, if the game/user gives a protocol, it will use only that protocol, if none is given, then it will try wss, and then ws in that order.

**Comment by kindasneaki** [comment]
Hollow Knight just needs to update the .net multiclient lib and it will be able to support it. I dont know who would be able to do that. I dont know if it would be worth it for HK to just wait until jarno updates the lib to support automatic SSL.

**Comment by kindasneaki** [comment]
I Should also add the RoR2 needs manual wss://

**Comment by Jarno458** [comment]
Timespniner was updated
BK_Sudoku was updated

The Messenger was attempted but fail to implement this

**Comment by N00byKing** [comment]
As no issues with SSL in V6 were reported, I've now also updated sm64 to utilize the new APCpp version

**Comment by Jarno458** [comment]
Simular to The Messenger, Hylics also does not work on wss

**Comment by Berserker66** [comment]
Subnautica has stable version out that switches ws/wss in mod and a testing version in the discord channel that relies on the library instead. I tested both versions in regards to this functionality.

**Comment by ScipioWright** [comment]
Stardew and DLCQuest were updated and no longer needs the user to input wss://
Overcooked 2 requires the user to input wss://
The Witness was updated to work
There's some sort of modified multiclient that makes Hollow Knight work, I'm iffy on the details. It should be in the Hollow Knight discord chat somewhere.
SA2B works with a pre-release version.
SM64 works with a newer version just like with V6, like N00by said.

**Comment by BadMagic100** [comment]
As implied by the linked issue above - HK can be checked off as of next release

**Comment by kindasneaki** [comment]
Muse Dash works with wss

**Comment by FelicitusNeko** [comment]
hxArchipelago (and thus Bumper Stickers) confirmed working with WSS. Will downgrade automatically but not upgrade. Shouldn't be too much trouble getting it working in both directions.

**Comment by Marechal-L** [comment]
The current build of DS3 works with wss:// ( Already checked on this list anyway )

**Comment by Seldom-SE** [comment]
It works for Terraria

**Comment by black-sliver** [comment]
@alwaysintreble @TRPG0 the fake websocket-sharp now has a "final" build (linked above). Let me know when you tested it and released a mod update, so we can check it off the list.

@KonoTyran any update on the minecraft mod release?

**Comment by alwaysintreble** [comment]
The Messenger now supports SSL https://github.com/alwaysintreble/TheMessengerRandomizerModAP/releases/tag/v0.11.8

**Comment by TRPG0** [comment]
Hylics 2 has been updated https://github.com/TRPG0/ArchipelagoHylics2/releases/tag/1.0.6

**Comment by BrandenEK** [comment]
Blasphemous has been updated

**Comment by KonoTyran** [comment]
WSS Compatible Minecraft client has been promoted from beta to release.
