### ISSUE TITLE
Core: Migration Tracking for Per-Game Data Packages (PR #1933)

### ISSUE THREAD

**Issue by ThePhar** [ArchipelagoMW/Archipelago#3394]
### What task needs to be completed?

Opening an issue to track the games currently merged in core and libraries documented in the network protocol documentation if they are updated to handle the changes from #1933, which removes the unique id constraint for items and locations across multiple games (as well as removal of `version` from the data package`).

Here is the list of libraries and games (as of 2024/05/24):

## Libraries

Mark a library as complete if it does not rely on `version` in the data package and can handle duplicate ids in the data package.

- [x] [CommonClient](https://github.com/ArchipelagoMW/Archipelago) (#1933)
- [x] [Archipelago.MultiClient.Java](https://github.com/ArchipelagoMW/Archipelago.MultiClient.Java)
- [x] [Archipelago.MultiClient.Net](https://www.nuget.org/packages/Archipelago.MultiClient.Net)
- [x] [apclientpp](https://github.com/black-sliver/apclientpp)
- [x] [APCpp](https://github.com/N00byKing/APCpp)
- [x] [archipelago.js](https://www.npmjs.com/package/archipelago.js)
- [ ] [hxArchipelago](https://lib.haxe.org/p/hxArchipelago)
- [ ] [ArchipelagoRS](https://github.com/ryanisaacg/archipelago_rs)
- [x] [lua-apclientpp](https://github.com/black-sliver/lua-apclientpp)
- [x] [gm-apclientpp](https://github.com/black-sliver/gm-apclientpp)
- [ ] [GM: Studio 2](https://github.com/PrintOmnivore20/archipelago-gamemaker-integration-sample)

## Game Clients

Mark a client as complete if it can handle duplicate ids in the data package. Libraries these clients rely on are also listed, which may require a library update as well. 

  - [x] **A Hat in Time** (CommonClient)
- [ ] **A Short Hike** (Archipelago.MultiClient.Net)
- [ ] **Adventure** (CommonClient)
- [ ] **Aquaria** (apclientpp)
- [x] **ArchipIDLE** (archipelago.js)
- [ ] **Blasphemous** (Archipelago.MultiClient.Net)
- [ ] **Bomb Rush Cyberfunk** (Archipelago.MultiClient.Net)
- [ ] **Bumper Stickers** (hxArchipelago)
- [x] **Castlevania 64** (CommonClient)
- [ ] **Celeste 64** (Archipelago.MultiClient.Net)
- [ ] **ChecksFinder** (CommonClient)
- [x] **Clique** (archipelago.js)
- [ ] **DLC Quest** (Archipelago.MultiClient.Net)
- [ ] **DOOM 1993** (APCpp)
- [ ] **DOOM II** (APCpp)
- [ ] **Dark Souls III** (apclientpp)
- [ ] **Donkey Kong Country 3** (CommonClient)
- [x] **Factorio** (CommonClient)
- [ ] **Final Fantasy** (CommonClient)
- [ ] **Final Fantasy Mystic Quest** (CommonClient)
- [ ] **Heretic** (APCpp)
- [ ] **Hollow Knight** (Archipelago.MultiClient.Net)
- [ ] **Hylics 2** (Archipelago.MultiClient.Net)
- [ ] **Kingdom Hearts 2** (CommonClient)
- [ ] **Kirby's Dream Land 3** (CommonClient)
- [ ] **Landstalker: The Treasures of King Nole** (apclientpp)
- [x] **Lingo** (_Custom Implementation_)
- [ ] **Lufia II Ancient Cave** (CommonClient)
- [ ] **Mario & Luigi: Superstar Saga** (CommonClient)
- [ ] **Mega Man Battle Network 3: Blue Version** (CommonClient)
- [x] **Meritous** (apclientpp)
- [ ] **Minecraft** (Archipelago.MultiClient.Java)
- [ ] **Muse Dash** (Archipelago.MultiClient.Net)
- [x] **Noita** (lua-apclientpp)
- [ ] **Overcooked! 2** (Archipelago.MultiClient.Net)
- [ ] **Pokemon Emerald** (CommonClient)
- [ ] **Pokemon Red and Blue** (CommonClient)
- [ ] **Raft** (Archipelago.MultiClient.Net)
- [ ] **Risk of Rain 2** (Archipelago.MultiClient.Net)
- [ ] **Rogue Legacy** (Archipelago.MultiClient.Net)
- [ ] **SMZ3** (CommonClient)
- [x] **Secret of Evermore** (apclientpp)
- [ ] **Shivers** (Archipelago.MultiClient.Net)
- [ ] **Slay the Spire** (Archipelago.MultiClient.Java)
- [x] **Sonic Adventure 2: Battle** (APCpp)
- [ ] **Starcraft 2** (CommonClient)
- [ ] **Stardew Valley** (Archipelago.MultiClient.Net)
- [x] **Subnautica** (Archipelago.MultiClient.Net)
- [ ] **Super Mario 64** (APCpp)
- [ ] **Super Mario World** (CommonClient)
- [ ] **SuperMetroid** (CommonClient)
- [x] **TUNIC** (Archipelago.MultiClient.Net)
- [ ] **Terraria** (Archipelago.MultiClient.Net)
- [x] **The Legend of Zelda** (CommonClient)
- [x] **The Legend of Zelda: A Link to the Past** (CommonClient)
- [ ] **The Legend of Zelda: Link's Awakening DX** (CommonClient)
- [ ] **The Legend of Zelda: Ocarina of Time** (CommonClient)
- [ ] **The Messenger** (Archipelago.MultiClient.Net)
- [x] **The Witness** (apclientpp)
- [x] **Timespinner** (Archipelago.MultiClient.Net)
- [ ] **Undertale** (CommonClient)
- [ ] **VVVVVV** (APCpp)
- [ ] **Wargroove** (Archipelago.MultiClient.Net)
- [ ] **Yoshi's Island** (CommonClient)
- [ ] **Yu-Gi-Oh! Ultimate Masters: World Championship Tournament 2006** (CommonClient)
- [ ] **Zillion** (CommonClient)
- [x] **Zork Grand Inquisitor** (CommonClient)

**Comment by Jarno458** [comment]
All APCpp games should just work as it next exposed id lookups https://discord.com/channels/731205301247803413/1182139198094987274/1243335972830056528

**Comment by ThePhar** [comment]
> All APCpp games should just work as it next exposed id lookups [discord.com/channels/731205301247803413/1182139198094987274/1243335972830056528](https://discord.com/channels/731205301247803413/1182139198094987274/1243335972830056528)

Thanks, marked the library as ready. Just need to validate the games have updated.

**Comment by hatkirby** [comment]
Small correction: the Lingo client doesn't use a library for AP (the autotracker does use apclientpp though).

**Comment by ThePhar** [comment]
> Small correction: the Lingo client doesn't use a library for AP (the autotracker does use apclientpp though).

I'll update it then. Do I assume the client still needs to update to support the changes from the PR?

**Comment by hatkirby** [comment]
It does, yeah. I would've just updated it before commenting but I probably won't be able to get to it until the weekend.

**Comment by NewSoupVi** [comment]
The Witness has updated to the newest version of apclientpp on its main branch, so next version I release will be compatible :)

**Comment by hatkirby** [comment]
The Lingo client is compatible with this as of v3.0.2. I also looked through the Lingo autotracker and determined that no updates are needed.

**Comment by Jarno458** [comment]
V6+ of Archipelago.Multiclient.Net will have support for this, an rc is currently available: https://github.com/ArchipelagoMW/Archipelago.MultiClient.Net/releases

**Comment by FelicitusNeko** [comment]
Meritous has been updated with latest apclientpp and adapted for 0.5.0 changes.

**Comment by Jarno458** [comment]
Official release for the c# lib with support for this: https://github.com/ArchipelagoMW/Archipelago.MultiClient.Net/releases/tag/6.0.0

**Comment by Jarno458** [comment]
An updated version of Timespinner is now available: https://github.com/Jarno458/TsRandomizer/releases/tag/v1.28.0

**Comment by ScipioWright** [comment]
TUNIC's update to the new lib is done now, so it works with 1933

**Comment by nbrochu** [comment]
Zork is CommonClient BTW

**Comment by nbrochu** [comment]
Zork Grand Inquisitor is `CommonClient` and not `Archipelago.MultiClient.Net`.

I wasn't using `version` in my world, so assuming it will just work for free. Give me a heads up if not.

**Comment by FelicitusNeko** [comment]
Work has finally started on hxArchipelago. Code changes are done, just needs testing/tweaking.

**Comment by FelicitusNeko** [comment]
hxArchipelago and Bumper Stickers have been updated.

**Comment by Jarno458** [comment]
So looking at the build in tracking inside the c# lib
https://discord.com/channels/731205301247803413/1043855558303821844/1128022069356003349

The following c# based games where updated to v6+ 
Hylics 2
Muse Dash
Raft
Risk of Rain
Shivers
Stardev Valley
Subnautica
The Messenger

Ofcourse i have no idea to know if this was just the dev testing, or was an actuall released version

**Comment by BadMagic100** [comment]
HK is updated as of client 0.5.0

**Comment by Jarno458** [comment]
I checked again based on buildin logging in the .net muticlient lib
it seems only 
Celeste 64
Overcooked! 2

are not yet migrated to the v6 version of library

**Comment by NewSoupVi** [comment]
I'm separately tracking which clients actually **force** you to be 1933 compliant and don't even have a "compatibility" layer anymore

- [] CommonClient - Currently only warns
- [x] Archipelago.MultiClient.Java - Completely abstracted, so it's handled "in the background"
- [x] Archipelago.MultiClient.Net - Completely abstracted, so it's handled "in the background"
- [x] apclientpp - Old code literally won't compile, as the function signature has been changed to include `std::string game` and the old function signature has been removed
- [] APCpp
- [] archipelago.js
- [] hxArchipelago
- [] ArchipelagoRS
- [] lua-apclientpp
- [] gm-apclientpp
- [] GM: Studio 2

**Comment by black-sliver** [comment]
@NewSoupVi apclientpp + lua + gm now requires you to explicitly opt into any old behaviour (by passing an empty string), I think that qualifies as forcing you to embrace the new API? Or do you need me to remove the old code path completely to satisfy your demands?

**Comment by NewSoupVi** [comment]
It's fine lol, yeah as long as it is less intuitive to do it the old way, I'm fine

**Comment by SunCatMC** [comment]
@ThePhar CommonClient version of checksfinder is basically unsupported, and my plan was to remove that file whenever i make client-breaking updates to apworld
If i don't do those changes when this pr is close to completion, i can remove the file earlier. Should i create a pr for removal of the old client to add progress to this pr, just have it wait on "other" so it's not merged early?

latest client currently doesn't handle datapackages at all, but i will keep these changes in mind when implementing proper handling of messages from the server

**Comment by ScipioWright** [comment]
Games that don't follow this should be broken or mostly broken at this point, closing this
