### ISSUE TITLE
Archipelago 0.6.0 Tracking

### ISSUE THREAD

**Issue by black-sliver** [ArchipelagoMW/Archipelago#4065]
### What task needs to be completed?

- [ ] Drop py3.8 support
- [ ] Add py3.13 support
- [ ] Update docs for supported py versions
- [ ] Drop `versions` from CommonClient
- [ ] Remove `persistent_load()` "datapackage" (and delete when saving?)
- [ ] Remove back compat of
  - [ ] ... list which ones ...
- [ ] Hard deprecate back compat of
  - [ ] ... list which ones ...

Post what you want to add to core (and deprecate) below.

**Comment by Berserker66** [comment]
Some of the progress is in https://github.com/ArchipelagoMW/Archipelago/pull/3973

**Comment by black-sliver** [comment]
I think I'd like to try
* bundling and versioning the CSS files:
  * use source files for DEBUG=True
  * use unique filenames for the bundles with DEBUG=False so we can enable proper cache control for them
* recompressing / optimizing the images:
  * check if sizes make sense, if not rescale
  * zopflipng them
  * convert them to webp and check if it makes sense to switch
  * preferably keep both png and webp in
* update SoE (not a core feature though)

**Comment by nicholassaylor** [comment]
Everything in #914 should probably be taken care of

**Comment by black-sliver** [comment]
I added it to the milestone

**Comment by nicholassaylor** [comment]
#4170 Depends on not being on Py3.8 and will have to wait for post-0.5.x

**Comment by ElGrenier** [comment]
Sorry to necropost but, since we are at 0.6.7, isn't this outdated and maybe closed or something ?
