### ISSUE TITLE
Tests: Update worlds to use bases.py rather than TestBase.py 

### ISSUE THREAD

**Issue by nicholassaylor** [ArchipelagoMW/Archipelago#4135]
### What task needs to be completed?

The following worlds still import TestBase.py and should be updated to import bases.py instead.

- [x] Bumper Stickers `test/__init__.py` #4137
- [x] Dark Souls III `test/TestDarkSouls3.py` #4138
- [x] DLC Quest `test/__init__.py` #4141 
- [x] Link to the Past (in various places) #4140
- [x] LADX `test/__init__.py` #4139
- [x] Lufia 2 AC `test/__init__.py` #4136
- [x] Pokemon Emerald `test/__init__.py` and `test/test_warps.py` #4142
