### ISSUE TITLE
Implement planned protocol changes

### ISSUE THREAD

**Issue by black-sliver** [ArchipelagoMW/Archipelago#813]
## Protocol changes
* Drop Print in favour of PrintJSON. At least multiclient.net can't handle arbitrary `type` yet, so version check is required.
* Drop support for missing `items_handling` in Connect
* Replace DataPackage `version` by a `hash`
* Drop `datapackage_version` from RoomInfo
* Drop `players` from RoomInfo
* Change `games` in RoomInfo to be a Set, including "Archipelago"

#### Stage 1: Verify client lib support of revamped `games` in RoomInfo and missing `players`
- [ ] apclientpp
- [ ] apcpp: 
- [ ] java
- [ ] js
- [ ] net
- [ ] py

#### Stage 2: Update clients that require update from stage 1
*insert items here when we know*

#### Stage 3: Implement new features, in the server
- [ ] Use PrintJSON for Chat and Countdown - fall back to Print for old clients (Connect `version`: *TBD*)
- [ ] Require `items_handling` in Connect for new clients (Connect `version`: *TBD*)
- [ ] Datapackage per-game checksum - in addition to version integer
- [ ] `games` revamp in RoomInfo (depends on stage1 and 2 being completed)

#### Stage 4: Implement new features in client libs, send new version
- [ ] apclientpp
- [ ] apcpp: 
- [ ] java
- [ ] js
- [ ] net
- [ ] py

#### Stage 5: Update clients to new libs
*insert all games here*

#### Stage 6: Drop backwards-compat in server
- [ ] Drop fallback to Print
- [ ] Drop version check from items_handling requirement
- [ ] Drop per-game integer datapackage version and RoomInfo datapackage_version
- [ ] Update minimum required client version in server

#### Stage 7: Drop backwards-compat in client
At the discretion of client lib devs, but should not happen before *TBD*.

## Random Notes
We may want a demo-server to test stage 1.

**Comment by Berserker66** [comment]
A fair few py world changes are done in https://github.com/ArchipelagoMW/Archipelago/pull/757

**Comment by Jarno458** [comment]
changes for countdown by PrintJSON are in #812 (still need to implement backward comaptibility)

**Comment by black-sliver** [comment]
* Fixed/split the datapackage version stuff above (it's still confusing...) with both version and versions.
* Added dropping `exclusions` from GetDataPackage. I already forgot that is still in :D

**Comment by Jarno458** [comment]
So regarding the .net client updates, the v4 was just released a couple of hours ago
Timespinner and Subnautica already use it
I'll gently poke the maintainers of the other .net games to see if they got time to update thiers

**Comment by KonoTyran** [comment]
can confirm Java library is compatible with stage 1. current Minecraft mod connects to games run with #757 without issue.

**Comment by Jarno458** [comment]
can confirm ArchipIDLE works just fine

**Comment by Jarno458** [comment]
Raft is also updated so can be checked off

**Comment by Jarno458** [comment]
RL was also updated and can be marked off

**Comment by ThePhar** [comment]
RoR2 has been updated, so marked it off. May also want to add removing forced_auto_forfeit to this as all clients after the next RoR2 client update should no longer be dependent on it.

**Comment by Jarno458** [comment]
As an update for step 6 "Drop fallback to Print" was already merged

**Comment by Jarno458** [comment]
Checksum based datapackage where added in https://github.com/ArchipelagoMW/Archipelago.MultiClient.Net v5.0.0
